version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfiles/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/env/dev.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    env_file:
      - ./backend/env/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
