version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfiles/Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ./backend/env/prod.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfiles/Dockerfile.prod
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:15
    env_file:
      - ./backend/env/prod.db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
