version: '3.8'

services:
  dev_backend:
    build:
      context: ./backend
      dockerfile: Dockerfiles/Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./backend/env/dev.env
    volumes:
      - ./backend:/app
    depends_on:
      - dev_db

  dev_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfiles/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  dev_db:
    image: postgres:15
    env_file:
      - ./backend/env/dev.env
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data

volumes:
  dev_postgres_data:
