version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=dev_username
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
