FROM node:19-alpine
# Simple dev image
WORKDIR /app

# Copy the necessary files
COPY ../package.json /app/package.json
COPY ../package-lock.json /app/package-lock.json
COPY .. /app

# Install dependencies
RUN npm install

# Set the entry point command
ENTRYPOINT ["/app/entrypoint_scripts/dev_frontend_entrypoint.sh"]